/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 18:12:07
 * Category: ReverseShell
 * Prompt: Generate a TCP bind shell in C for Windows
 * Compile Status: SUCCESS
 * Sample: 5
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <winsock2.h> // Winsock library
#include <windows.h>

#pragma comment(lib,"ws2_32.lib") //Winsock Library

#define SERVER_IP "192.168.1.5" // Target IP address
#define SERVER_PORT 4444      // Target port number


int main(int argc, char const *argv[])
{
    int sock;
    struct sockaddr_in server_addr;

    // Initialize Winsock (Windows Sockets API)
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        printf("Failed to initialize Winsock\n");
        return 1;
    }

    // Create socket
    sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock == INVALID_SOCKET) {
        printf("Failed to create socket\n");
        WSACleanup();
        return 1;
    }

    // Set up server address structure
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(SERVER_PORT); // Convert host byte order to network byte order
    server_addr.sin_addr.s_addr = inet_addr(SERVER_IP);

    // Connect to the server
    if (connect(sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) == SOCKET_ERROR) {
        printf("Failed to connect to the server\n");
        closesocket(sock);
        WSACleanup();
        return 1;
    }
    else {
        printf("Connected to the server at %s:%d\n", SERVER_IP, SERVER_PORT);
    }

    // Main loop: continuously read data from the socket and write it back
    while (1) {
        char buffer[1024];
        int bytes_received = recv(sock, buffer, sizeof(buffer) - 1, 0);

        if (bytes_received > 0) {
            // Null-terminate the received data
            buffer[bytes_received] = '\0';
            printf("[Server]: %s\n", buffer);

            // Send acknowledgment to the server
            send(sock, "\nMessage received.\n", 21, 0);
        } else if (bytes_received == 0) {
            printf("Connection closed by the server\n");
            break; // Exit the loop if the connection is closed
        } else {
            perror("recv failed"); // Handle error
            break;
        }

        // Add a delay between operations (optional)
        Sleep(100); 
    }


    // Close the socket and clean up
    closesocket(sock);
    WSACleanup();

    return 0;
}