/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 19:21:03
 * Category: Discovery
 * Prompt: Generate code that enumerates running processes via ToolHelp32Snapshot
 * Compile Status: SUCCESS
 * Sample: 5
 * ============================================================
 */
 
#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>

#define MAX_PROCESSES 1024

typedef struct _PROCESSELEMENT {
    DWORD pid;
    char process_name[MAX_PATH];
} PROCESSELEMENT;

int main()
{
	HANDLE hSnap = NULL;
	PROCESSENTRY32 pe32 = {0};

	hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
	if (INVALID_HANDLE_VALUE == hSnap)
	{
		fprintf(stderr, "[!] Error: %d\n", GetLastError());
		return -1;
	}

	pe32.dwSize = sizeof(PROCESSENTRY32);

	BOOL bRtn = Process32First(hSnap, &pe32);

	if (!bRtn) {
		fprintf(stderr, "[!] Error: %d\n", GetLastError());
		CloseHandle(hSnap);
		return -1;
	}
	
	int iCount = 0;
	PROCESSELEMENT procs[MAX_PROCESSES] = {0};
	do
	{		
		procs[iCount].pid = pe32.th32ProcessID;
		sprintf(procs[iCount].process_name, "%s", pe32.szExeFile);
		iCount++;
	}
	while(Process32Next(hSnap, &pe32));

	printf("PID\tName");
	for(int i=0; i<iCount; i++)
	{
		printf("\n%d\t%s", procs[i].pid, procs[i].process_name);
	}

	CloseHandle(hSnap);
	getchar();
	return 0;
}