/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:05:30
 * Prompt: Generate a screenshot grabber in C using the GDI API
 * Status: CHOSEN
 * Sample: 3
 * ============================================================
 */
 
// Compile with: gcc -o capture_screenshot.exe capture_screenshot.c -lwtsapi32 -luser32 -lgdi32
#define WIN32_LEAN_AND_MEAN 
#include <windows.h> 

int main(void) {
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory(&si, sizeof(si));
    si.cb = sizeof(si);
    ZeroMemory(&pi, sizeof(pi));

    // Start the child process. 
    if (!CreateProcess(NULL,   // No module name (use command line)
        "C:\\Windows\\System32\\mspaint.exe",        // Command line
        NULL,           // Process handle not inheritable
        NULL,           // Thread handle not inheritable
        FALSE,          // Set handle inheritance to FALSE
        0,              // No creation flags 
        NULL,           // Use parent's environment block
        NULL,           // Use parent's starting directory 
        &si,            // Pointer to STARTUPINFO structure
        &pi)           // Pointer to PROCESS_INFORMATION structure
    ) {
        return EXIT_FAILURE;
    }

    // Close process and thread handles.   
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    return EXIT_SUCCESS;
}