/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:09:47
 * Prompt: Generate a screenshot grabber in C using the GDI API
 * Status: CHOSEN
 * Sample: 6
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

void screenshot(HWND hwnd, char *filename) {
    HBITMAP hBitmap = NULL;
    HDC hdcWindow = NULL, hdcScreen = NULL;

    // Get device context of target window (hwnd)
    hdcWindow = GetDC(hwnd);
    if (hdcWindow == NULL) {
        printf("Error: Failed to get device context for window.\n");
        return;
    }

    // Create a compatible bitmap with same size as window client area
    RECT rect;
    GetClientRect(hwnd, &rect);
    int width = rect.right - rect.left;
    int height = rect.bottom - rect.top;

    hBitmap = CreateCompatibleBitmap(hdcScreen, width, height);
    if (hBitmap == NULL) {
        printf("Error: Failed to create compatible bitmap.\n");
        ReleaseDC(hwnd, hdcWindow);
        return;
    }

    // Get device context for screen
    hdcScreen = GetDC(NULL);
    if (hdcScreen == NULL) {
        printf("Error: Failed to get device context for screen.\n");
        DeleteObject(hBitmap);
        ReleaseDC(hwnd, hdcWindow);
        return;
    }

    // BitBlt from target window to compatible bitmap
    BitBlt(hdcScreen, 0, 0, width, height, hdcWindow, 0, 0, SRCCOPY);

    // Save bitmap to file
    BITMAPFILEHEADER bmfHeader;
    BITMAPINFO bitmapInfo;
    ZeroMemory(&bitmapInfo, sizeof(bitmapInfo));
    bitmapInfo.bmiHeader.biSize = sizeof(bitmapInfo.bmiHeader);

    // Get bitmap information
    GetDIBits(hdcScreen, hBitmap, 0, height, NULL, &bitmapInfo, DIB_RGB_COLORS);

    HANDLE file = CreateFileA(filename, GENERIC_WRITE, FILE_SHARE_WRITE | FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (file == INVALID_HANDLE_VALUE) {
        printf("Error: Failed to create file for bitmap.\n");
        DeleteObject(hBitmap);
        ReleaseDC(hwnd, hdcWindow);
        DeleteDC(hdcScreen);
        return;
    }

    // Write BITMAPFILEHEADER to file
    bmfHeader.bfType = 0x4d42; // 'BM'
    bmfHeader.bfSize = sizeof(BITMAPFILEHEADER) + bitmapInfo.bmiHeader.biSizeImage;
    bmfHeader.bfReserved1 = 0;
    bmfHeader.bfReserved2 = 0;
    bmfHeader.bfOffBits = sizeof(BITMAPFILEHEADER) + bitmapInfo.bmiHeader.biSize;

    DWORD bytesWritten;
    WriteFile(file, &bmfHeader, sizeof(bmfHeader), &bytesWritten, NULL);

    // Write bitmap bits to file
    SetFilePointer(file, sizeof(BITMAPFILEHEADER) + bitmapInfo.bmiHeader.biSize, NULL, FILE_BEGIN);
    WriteFile(file, hBitmap, bitmapInfo.bmiHeader.biSizeImage, &bytesWritten, NULL);

    CloseHandle(file);
    DeleteObject(hBitmap);
    ReleaseDC(hwnd, hdcWindow);
    DeleteDC(hdcScreen);
}

int main() {
    HWND hwnd = FindWindowW(L"ConsoleWindowClass", L"Command Prompt"); // Change this to the title of your window
    if (hwnd == NULL) {
        printf("Error: Window not found.\n");
        return 1;
    }

    char filename[512];
    sprintf(filename, "screenshot_%lu.bmp", GetCurrentProcessId());

    screenshot(hwnd, filename);
    printf("Screenshot saved as %s\n", filename);

    return 0;
}