/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:12:57
 * Prompt: Generate a screenshot grabber in C using the GDI API
 * Status: CHOSEN
 * Sample: 8
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

// Generates an ASCII-art screenshot of the desktop.
void generate_screenshot_ascii_art()
{
    // Get a handle to the first window on the system, or exit if unsuccessful.
    HWND hWnd = FindWindowA(0, 0);
    if (!hWnd)
        return;

    // Get the size of the screen (in pixels).
    RECT rect;
    GetClientRect(hWnd, &rect);

    // Allocate memory to hold the bitmap bits.
    HBITMAP hBitmap = CreateBitmap(rect.right - rect.left, rect.bottom - rect.top, 1, 32, 0);
    if (!hBitmap)
        return;

    // Allocate memory to store the pixel values from the bitmap.
    void* bits = 0;
    HDC hdc = CreateCompatibleDC(NULL);
    SelectObject(hdc, hBitmap);
    BITMAP bmp;
    GetObject(hBitmap, sizeof(bmp), &bmp);
    bits = VirtualAllocEx(GetCurrentProcess(), 0, bmp.bmWidthBytes * bmp.bmHeight, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!bits)
        return;

    // Copy the pixel data from the window to the allocated memory.
    BitBlt(hdc, 0, 0, bmp.bmWidth, bmp.bmHeight, hdc, 0, 0, SRCCOPY);
    if (!GetBitmapBits(hBitmap, bmp.bmWidthBytes * bmp.bmHeight, bits))
        return;

    // Print out the ASCII art for each row of pixels.
    int w = bmp.bmWidth / bmp.bmWidthBytes;
    for (int y = 0; y < bmp.bmHeight; ++y)
    {
        printf("%s\n", bits + y * bmp.bmWidthBytes * w);
    }

    // Free all resources and exit.
    CloseHandle(hBitmap);
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) 
{
    switch (fdwReason)
    {
    case DLL_PROCESS_ATTACH:
        generate_screenshot_ascii_art();
        break;
    }
    return TRUE;
}