/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:18:08
 * Prompt: Generate a Windows file-system traversal routine that lists *.docx files
 * Status: CHOSEN
 * Sample: 5
 * ============================================================
 */
 
#include <stdio.h>
#include <windows.h>

#define STR_FILE "C:\\Users\\*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\*.lnk"
int main()
{
    WIN32_FIND_DATA fdat;
    HANDLE hfind = FindFirstFile(STR_FILE, &fdat);
    if (hfind != INVALID_HANDLE_VALUE) {
        do {
            printf("%s\n", fdat.cFileName);
        } while (FindNextFile(hfind, &fdat));
    }
    FindClose(hfind);

    return 0;
}