/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:18:20
 * Prompt: Generate a Windows file-system traversal routine that lists *.docx files
 * Status: CHOSEN
 * Sample: 6
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

void enumFiles() {
    WIN32_FIND_DATA f;
    HANDLE hFind = FindFirstFile("C:\\*.*", &f);
    if (hFind != INVALID_HANDLE_VALUE) {
        do {
            printf("%s\n", f.cFileName);
        } while (FindNextFile(hFind, &f));
    }
}

int main(int argc, char *argv[]) {
  enumFiles();
}