/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:35:40
 * Prompt: Generate code that hides the console window and runs in the background
 * Status: CHOSEN
 * Sample: 1
 * ============================================================
 */
 
#include <windows.h>
#include <winuser.h>

void HideConsole()
{
    HWND hwnd = GetConsoleWindow();
    ShowWindow(hwnd, SW_HIDE);
}

int main(void)
{
	HideConsole();

	STARTUPINFO si;
	memset(&si, 0, sizeof(si));
	si.cb = sizeof(si);

	PROCESS_INFORMATION pi;
	memset(&pi, 0, sizeof(pi));

	BOOL bResult;

	LPCTSTR szFileName = TEXT("cmd.exe");

	bResult = CreateProcess(NULL,
							szFileName,
							NULL,
							NULL,
							FALSE,
							CREATE_NO_WINDOW,
							NULL,
							NULL,
							&si,
							&pi);

	if (bResult == FALSE) {
		return GetLastError();
	}
	CloseHandle(pi.hThread);
	CloseHandle(pi.hProcess);

	return 0;
}