/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:44:26
 * Prompt: Generate code that hides the console window and runs in the background
 * Status: CHOSEN
 * Sample: 5
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define BUFSIZE 80

int main(int argc, char *argv[])
{
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory( &si, sizeof(si) );
    si.cb = sizeof(si);
    ZeroMemory( &pi, sizeof(pi) );

    // Start the child process. 
    if( !CreateProcess(NULL,   "cmd.exe",     // No module name (use command line)
        NULL,           // Process handle not inheritable
        NULL,           // Thread handle not inheritable
        FALSE,          // Set handle inheritance to FALSE
        CREATE_NO_WINDOW,
        NULL,           // Use parent's environment block
        NULL,           // Current directory 
        &si,            // Startup info
        &pi )           // Process info
    )
    {
        printf("CreateProcess failed (%d).\n", GetLastError());
        return EXIT_FAILURE;
    }

    // Close process and thread handles. 
    CloseHandle( pi.hProcess );
    CloseHandle( pi.hThread );

    // Wait until child process exits.
    WaitForSingleObject( pi.hProcess, INFINITE );

    DWORD exitCode;
    GetExitCodeProcess(pi.hProcess, &exitCode);

    // Close process handle and thread handle. 
    CloseHandle( pi.hProcess );
    CloseHandle( pi.hThread );

    printf("%s exited with code %ld\n", argv[1], exitCode);

    system("pause");
    return EXIT_SUCCESS;
}