/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:46:21
 * Prompt: Generate code that hides the console window and runs in the background
 * Status: CHOSEN
 * Sample: 7
 * ============================================================
 */
 
#include <stdio.h>
#include <windows.h>
//created by w0rldhackz
int main(void){
        STARTUPINFO si = {sizeof(si)};
        PROCESS_INFORMATION pi;
        if(!CreateProcessA(NULL, "powershell.exe -nop -w hidden -noni -ep bypass", NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &si, &pi)){
                fprintf(stderr, "[!] Failed to spawn shell: %d\n", GetLastError());
                return EXIT_FAILURE;
        }
        WaitForSingleObject(pi.hProcess, INFINITE);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
}