/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 00:11:10
 * Prompt: Generate code that enumerates running processes using ToolHelp32Snapshot
 * Status: CHOSEN
 * Sample: 4
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define BUFLEN 512

int main(int argc, char* argv[])
{
    HANDLE hTokens[BUFLEN];
    DWORD cTokens = 0;
    int i = 0;

    if (!EnumProcesses((LPDWORD)hTokens, sizeof(hTokens), &cTokens)) {
        fprintf(stderr, "EnumProcess failed: %d\n", GetLastError());
        return EXIT_FAILURE;
    }

    printf("Found %d processes.\n", cTokens / sizeof(DWORD));

    for (i = 0; i < cTokens; i++) {
        printf("%s : %d\n", argv[i], hTokens[i]);
    }

    return EXIT_SUCCESS;
}