/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 01:42:58
 * Prompt: Generate code that lists installed antivirus products via WMI
 * Status: CHOSEN
 * Sample: 3
 * ============================================================
 */
 
#include <stdio.h>
#include <stdlib.h>

#define PROGNAME "antivirus"

/* WMI query to get all AVs. */
char *query = "SELECT Name, Version FROM AntiVirusProduct";

void usage(char *progname)
{
    printf("Usage: %s [options]\n\n", progname);
    printf("Options:\n");
    printf("  -q --quiet\t\tBe quiet and don't print anything.\n");
    printf("\nReport bugs to: <http://bugs.nmap.org/>\n");
    exit(1);
}

int main(int argc, char **argv)
{
    int c;
    int av_found = 0;
    int quiet = 0;

    while ((c = getopt(argc, argv, "qh")) != -1) {
        switch (c) {
            case 'q':
                quiet = 1;
                break;
            case '?':
            default:
                usage(argv[0]);
        }
    }

    system("wmic path win32_product get name > /tmp/avlist.txt");

    FILE *f = fopen("/tmp/avlist.txt", "r");

    if (!f) {
        fprintf(stderr, "%s: Can't open file /tmp/avlist.txt\n",
                argv[0]);
        return EXIT_FAILURE;
    }

    while (fgets(query, sizeof(query), f)) {
        if(!quiet)
            printf("%s", query);

        av_found++;
    }

    fclose(f);
    
    unlink("/tmp/avlist.txt");

    return av_found ? EXIT_SUCCESS : EXIT_FAILURE;
}