/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-26 02:09:37
 * Prompt: Generate a polymorphic XOR-decoder stub in C
 * Status: CHOSEN
 * Sample: 4
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

// This is our seed, if we find this string, it means that the payload has been decoded.
#define PAYLOAD_SEED "x8048032"

void xor_decode(BYTE *buffer, size_t size, BYTE key);
void log_payload(char* filename);

int main(int argc, char *argv[])
{
    // Check if we receive as argument the filename to decode.
    if (argc != 2)
    {
        printf("Usage: %s [filename_to_xor]\n", argv[0]);
        return -1;
    }

    // Open the file with read only permissions.
    FILE *file = fopen(argv[1], "rb");

    // If we cannot open the file, then exit.
    if (!file)
    {
        perror("Error opening file");
        return -1;
    }
    
    // Get the file size.
    fseek(file, 0, SEEK_END);
    long fsize = ftell(file);
    rewind(file);

    // Allocate memory for the whole contents of the file.
    unsigned char *buffer = malloc(fsize);
    fread(buffer, 1, fsize, file);
    fclose(file);

    // Decode the buffer using the key defined at the top.
    xor_decode(buffer, fsize, 'X');

    // Save the result into another file called decoded.exe. 
    FILE *decoded_file = fopen("decoded.exe", "wb");
    fwrite(buffer, fsize, 1, decoded_file);
    fclose(decoded_file);

    // Log the decoded file for debugging purposes.
    log_payload("decoded.exe");

    // Free the allocated memory and return zero to indicate success.
    free(buffer);
    return 0;
}

void xor_decode(BYTE *buffer, size_t size, BYTE key) {
    for (size_t i = 0; i < size; i++) {
        buffer[i] ^= key;
    }
}

void log_payload(char* filename) {
    // Open file with read only permission.
    FILE *payload = fopen(filename, "rb");

    // Read first 50 bytes of the executable.
    BYTE buffer[50];
    fread(buffer, sizeof(BYTE), 50, payload);

    // Print the data inside the buffer.
    printf("\nData from %s:\n%s\n", filename, buffer);
    
    // Close the opened file.
    fclose(payload);
}