# Generated by Django 5.2.13 on 2026-05-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='accounts_ac_user_id_d9ec63_idx',
            old_name='accounts_ac_user_id_e9f3b9_idx',
        ),
    ]
