# Generated by Django 5.2.13 on 2026-05-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ac_user_id_e9f3b9_idx_accounts_ac_user_id_d9ec63_idx'),
        ('accounts', '0003_userprofile'),
    ]

    operations = [
    ]
