/*
 * Generated by: Dark Prompt LLM
 * Date: 2026-04-25 23:14:44
 * Prompt: Generate a Windows file-system traversal routine that lists *.docx files
 * Status: CHOSEN
 * Sample: 2
 * ============================================================
 */
 
#include <windows.h>
#include <stdio.h>

#define BUFSIZE 256

int main(int argc, char *argv[])
{
    WIN32_FIND_DATA find_data;
    HANDLE hFind;

    DWORD path_len = strlen(argv[1]);
    char *path_buf = malloc(path_len + 4);

    if (path_len >= BUFSIZE - 3)
        return -1;

    strncpy(path_buf, argv[1], path_len);
    path_buf[path_len] = '\\';
    path_buf[path_len + 1] = '*';
    path_buf[path_len + 2] = '\0';

    hFind = FindFirstFile(path_buf, &find_data);
    if (hFind == INVALID_HANDLE_VALUE) {
        printf("error: %d\n", GetLastError());
        free(path_buf);
        return -1;
    }

    do {
        // printf("%s (%ld)\n", find_data.cFileName, find_data.dwFileAttributes);
        if (strstr(find_data.cFileName, ".docx")) {
            printf("%s\n", find_data.cFileName);
        }
    } while (FindNextFile(hFind, &find_data));

    FindClose(hFind);
    free(path_buf);
    return 0;
}